name = "ActorInterfaces"
uuid = "7e194583-e687-41a0-9133-1c22a29c80af"
authors = ["Krisztián Schäffer" ,"Paul Bayer"]
version = "0.1.0"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
